apiVersion: v1
kind: Service
metadata:
  name: forest-api-service
spec:
  type: NodePort
  ports:
    - name: default
      port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: forest-api